// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw2pVFTLmipC_bBorCPhPfMaslpwAG09g',
    appId: '1:227252082418:web:901f0cb82999aea4a0226b',
    messagingSenderId: '227252082418',
    projectId: 'hairmainstreet',
    authDomain: 'hairmainstreet.firebaseapp.com',
    storageBucket: 'hairmainstreet.appspot.com',
    measurementId: 'G-5TQ40EVYFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvPZcSZT_qfdwObU5MHG_6sNcV18TiiJc',
    appId: '1:227252082418:android:9ac975310c3ae7f9a0226b',
    messagingSenderId: '227252082418',
    projectId: 'hairmainstreet',
    storageBucket: 'hairmainstreet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnNhezEHYFict13Ky9_Utma-TrKW-BedQ',
    appId: '1:227252082418:ios:61cc7329585359d3a0226b',
    messagingSenderId: '227252082418',
    projectId: 'hairmainstreet',
    storageBucket: 'hairmainstreet.appspot.com',
    iosBundleId: 'com.example.hairMainStreetAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnNhezEHYFict13Ky9_Utma-TrKW-BedQ',
    appId: '1:227252082418:ios:1a9e62fe186b6654a0226b',
    messagingSenderId: '227252082418',
    projectId: 'hairmainstreet',
    storageBucket: 'hairmainstreet.appspot.com',
    iosBundleId: 'com.example.hairMainStreetAdmin.RunnerTests',
  );
}
